//! Headless-Blender repair-script generation — the PLAN §7 **[decided]** fallback for the repairs
//! the native FBX writer deliberately only flags.
//!
//! [`plan_repairs`](crate::plan_repairs) splits a [`RepairPlan`] into *native* edits (bone renames,
//! applied by [`apply_plan`](crate::apply_plan)) and *flagged* edits — reparents and
//! scale/orientation normalization — that require re-transforming geometry, which this toolchain
//! does not do in Rust. [`blender_script`] emits a Python script that performs the **whole** plan
//! (renames included) in one headless Blender pass, because Blender's data model makes exactly the
//! flagged edits safe:
//!
//! * **Reparents** — Blender edit-bones store *absolute* head/tail transforms, so changing
//!   `edit_bones[b].parent` preserves the bone's world rest pose by construction. This is the
//!   "recompose the local transform against the new parent" a bare FBX `OO` edit can't do.
//! * **Scale / orientation** — the FBX importer converts into Blender's meter/Z-up world;
//!   `transform_apply` then bakes that conversion into the mesh/armature data, and the exporter
//!   writes a Unity-friendly file (`FBX_SCALE_ALL`, no leaf bones).
//! * **Renames** — `bone.name = new` in Blender also updates the skin vertex groups that key on
//!   the name, so the script is self-contained even when run on the *original* (un-renamed) FBX.
//!
//! The generated script is deterministic text; it is **not executed** by this crate (running it
//! needs a local Blender: `blender --background --python <script>`). The last mile — confirming
//! the exported FBX imports as a valid humanoid — remains the Unity-acceptance workflow's job.

use crate::repair::{RepairEdit, RepairPlan};

/// Render `plan` as a headless-Blender Python script that reads `input_fbx`, applies every edit
/// (renames, geometry-aware reparents, scale/orientation baking), and exports `output_fbx`.
///
/// Returns `None` when the plan has no edits at all — there is nothing for Blender to do.
pub fn blender_script(plan: &RepairPlan, input_fbx: &str, output_fbx: &str) -> Option<String> {
    if plan.is_empty() {
        return None;
    }

    let renames: Vec<(&str, &str)> = plan
        .edits
        .iter()
        .filter_map(|e| match e {
            RepairEdit::RenameBone { from, to, .. } => Some((from.as_str(), to.as_str())),
            _ => None,
        })
        .collect();
    // Reparent edits carry canonical (post-rename) names; the script applies renames first, so
    // these resolve whether it runs on the original or an already-renamed file.
    let reparents: Vec<(&str, &str)> = plan
        .edits
        .iter()
        .filter_map(|e| match e {
            RepairEdit::Reparent {
                bone, to_parent, ..
            } => Some((bone.as_str(), to_parent.as_str())),
            _ => None,
        })
        .collect();
    let needs_transform_bake = plan.edits.iter().any(|e| {
        matches!(
            e,
            RepairEdit::NormalizeScale { .. } | RepairEdit::NormalizeOrientation { .. }
        )
    });

    let mut s = String::new();
    s.push_str(
        "# Generated by `avatar armature fix --blender-script` — headless Blender repair pass.\n\
         # Run:  blender --background --python <this file>\n\
         #\n\
         # Applies the full repair plan: bone renames, geometry-aware reparents (Blender edit-bones\n\
         # hold absolute rest transforms, so reparenting preserves the rest pose), and — when the\n\
         # source file had non-standard units/axes — bakes the importer's unit/axis conversion into\n\
         # the data before a Unity-friendly export.\n\
         import bpy\n\n",
    );
    s.push_str(&format!("INPUT = \"{}\"\n", py_escape(input_fbx)));
    s.push_str(&format!("OUTPUT = \"{}\"\n\n", py_escape(output_fbx)));

    s.push_str("RENAMES = [\n");
    for (from, to) in &renames {
        s.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            py_escape(from),
            py_escape(to)
        ));
    }
    s.push_str("]\n");
    s.push_str("REPARENTS = [\n");
    for (bone, parent) in &reparents {
        s.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            py_escape(bone),
            py_escape(parent)
        ));
    }
    s.push_str("]\n\n");

    s.push_str(
        "bpy.ops.wm.read_factory_settings(use_empty=True)\n\
         bpy.ops.import_scene.fbx(filepath=INPUT)\n\n\
         armatures = [o for o in bpy.data.objects if o.type == 'ARMATURE']\n\
         if not armatures:\n\
         \x20   raise SystemExit(f\"no armature found in {INPUT}\")\n\
         arm = armatures[0]\n\
         bpy.context.view_layer.objects.active = arm\n\n\
         # Renames first: Blender propagates a bone rename to the vertex groups that skin to it,\n\
         # and the reparent list below uses the canonical (post-rename) names.\n\
         for old, new in RENAMES:\n\
         \x20   b = arm.data.bones.get(old)\n\
         \x20   if b is not None and b.name != new:\n\
         \x20       b.name = new\n\n\
         # Geometry-aware reparents: edit-bone heads/tails are absolute, so this preserves each\n\
         # bone's world rest pose — the reason this repair is Blender's job, not the FBX writer's.\n\
         bpy.ops.object.mode_set(mode='EDIT')\n\
         eb = arm.data.edit_bones\n\
         for bone, parent in REPARENTS:\n\
         \x20   if bone in eb and parent in eb:\n\
         \x20       eb[bone].use_connect = False\n\
         \x20       eb[bone].parent = eb[parent]\n\
         \x20   else:\n\
         \x20       print(f\"warning: could not reparent {bone!r} under {parent!r} (bone not found)\")\n\
         bpy.ops.object.mode_set(mode='OBJECT')\n\n",
    );

    if needs_transform_bake {
        s.push_str(
            "# The source file had a non-standard UnitScaleFactor and/or UpAxis. The importer\n\
             # normalized the scene into Blender's meter / Z-up world via object transforms; baking\n\
             # them makes the fix part of the data rather than metadata the next importer must undo.\n\
             bpy.ops.object.select_all(action='SELECT')\n\
             bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)\n\n",
        );
    }

    s.push_str(
        "bpy.ops.object.select_all(action='SELECT')\n\
         bpy.ops.export_scene.fbx(\n\
         \x20   filepath=OUTPUT,\n\
         \x20   apply_scale_options='FBX_SCALE_ALL',\n\
         \x20   add_leaf_bones=False,\n\
         \x20   use_selection=True,\n\
         )\n\
         print(f\"wrote {OUTPUT}\")\n",
    );

    Some(s)
}

/// Escape a string for a double-quoted Python literal.
fn py_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::repair::{RepairEdit, RepairPlan};

    fn full_plan() -> RepairPlan {
        RepairPlan {
            edits: vec![
                RepairEdit::RenameBone {
                    id: 7,
                    from: "mixamorig:LeftHand".into(),
                    to: "LeftHand".into(),
                },
                RepairEdit::Reparent {
                    id: 7,
                    bone: "LeftHand".into(),
                    from_parent: "mixamorig:Hips".into(),
                    to_parent: "LeftLowerArm".into(),
                    to_parent_id: 6,
                },
                RepairEdit::NormalizeScale {
                    from_unit_scale: 1.0,
                },
                RepairEdit::NormalizeOrientation { from_up_axis: 2 },
            ],
        }
    }

    #[test]
    fn script_covers_every_edit_class() {
        let script = blender_script(&full_plan(), "in.fbx", "out.fbx").expect("plan has edits");
        assert!(script.contains("import bpy"));
        assert!(script.contains("INPUT = \"in.fbx\""));
        assert!(script.contains("OUTPUT = \"out.fbx\""));
        assert!(script.contains("(\"mixamorig:LeftHand\", \"LeftHand\")"));
        assert!(script.contains("(\"LeftHand\", \"LeftLowerArm\")"));
        // Flagged normalization -> the transform bake block is present.
        assert!(script.contains("transform_apply"));
        assert!(script.contains("export_scene.fbx"));
    }

    #[test]
    fn transform_bake_only_when_flagged() {
        let plan = RepairPlan {
            edits: vec![RepairEdit::RenameBone {
                id: 1,
                from: "a".into(),
                to: "Hips".into(),
            }],
        };
        let script = blender_script(&plan, "in.fbx", "out.fbx").unwrap();
        assert!(!script.contains("transform_apply"));
    }

    #[test]
    fn empty_plan_yields_no_script() {
        assert!(blender_script(&RepairPlan::default(), "a.fbx", "b.fbx").is_none());
    }

    #[test]
    fn paths_are_escaped_for_python() {
        let plan = RepairPlan {
            edits: vec![RepairEdit::NormalizeScale {
                from_unit_scale: 1.0,
            }],
        };
        let script = blender_script(&plan, r#"C:\models\my "rig".fbx"#, "out.fbx").unwrap();
        assert!(script.contains(r#"INPUT = "C:\\models\\my \"rig\".fbx""#));
    }
}
