//! The lint engine: discover a Unity/VPM project, scan its VRChat assets, and report SDK3
//! compliance problems (parameter sync budget, duplicate parameters, menu size, dangling menu
//! parameter references) plus project/SDK info.
//!
//! Rules are intentionally conservative: errors are things VRChat will reject or that break the
//! avatar; warnings are likely-but-not-certain problems (e.g. a menu referencing a parameter we
//! can't find a declaration for, which may be generated by another tool at build time).

use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::path::Path;

use anyhow::{Context, Result};
use avatar_unity_asset::AnimatorController;
use avatar_unity_yaml::{UnityFile, Yaml, field_f64, field_i64, relative};
use avatar_vpm::{AVATAR_SDK, UnityProject};
use avatar_vrc_descriptor::{
    AssetRef, AvatarDescriptor, ExpressionParameters, ExpressionsMenu, MAX_MENU_CONTROLS,
    SYNC_BUDGET_BITS, VISEME_COUNT, ValueType, VrcAsset, extract,
};
use serde::Serialize;

mod builtins;
use builtins::BUILTIN_PARAMETERS;

/// How serious a lint finding is: an `Error` is something VRChat will reject or that breaks the
/// avatar, a `Warn` is a likely-but-uncertain problem, and `Info` is advisory only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum Severity {
    /// VRChat will reject this, or it breaks the avatar.
    Error,
    /// A likely-but-not-certain problem.
    Warn,
    /// Advisory information; not a problem on its own.
    Info,
}

impl Severity {
    pub fn label(self) -> &'static str {
        match self {
            Severity::Error => "error",
            Severity::Warn => "warn",
            Severity::Info => "info",
        }
    }
}

/// A single lint finding.
#[derive(Debug, Clone, Serialize)]
pub struct Diagnostic {
    pub severity: Severity,
    /// Stable rule code, e.g. `"VRC010"`.
    pub code: &'static str,
    pub message: String,
    /// Project-relative file path the finding refers to, if any.
    pub file: Option<String>,
    /// Optional remediation hint.
    pub hint: Option<String>,
}

/// The result of linting a project.
#[derive(Debug, Clone, Serialize)]
pub struct LintReport {
    pub project_root: String,
    pub unity_version: Option<String>,
    pub avatar_sdk_version: Option<String>,
    pub packages: Vec<PackageInfo>,
    pub parameter_assets: usize,
    pub menu_assets: usize,
    pub descriptors: usize,
    pub controllers: usize,
    pub diagnostics: Vec<Diagnostic>,
}

/// A VPM package found in the project's manifest (name and resolved version).
#[derive(Debug, Clone, Serialize)]
pub struct PackageInfo {
    pub name: String,
    pub version: String,
}

impl LintReport {
    pub fn error_count(&self) -> usize {
        self.count(Severity::Error)
    }
    pub fn warn_count(&self) -> usize {
        self.count(Severity::Warn)
    }
    fn count(&self, sev: Severity) -> usize {
        self.diagnostics
            .iter()
            .filter(|d| d.severity == sev)
            .count()
    }
}

/// Lint the project at or above `path`.
pub fn run(path: &Path) -> Result<LintReport> {
    let project = UnityProject::discover(path)?;
    let mut diagnostics = Vec::new();

    // --- Project / VPM checks ---
    if !project.has_avatar_sdk() {
        diagnostics.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC001",
            message: format!("VRChat avatar SDK ({AVATAR_SDK}) not found in vpm-manifest.json"),
            file: None,
            hint: Some("Add the Avatars package via the Creator Companion (VCC).".into()),
        });
    }

    // --- Collect VRChat assets ---
    let mut parameter_assets: Vec<(String, ExpressionParameters)> = Vec::new();
    let mut menu_assets: Vec<(String, ExpressionsMenu)> = Vec::new();
    let mut descriptors: Vec<(String, AvatarDescriptor)> = Vec::new();
    let mut controllers: Vec<(String, AnimatorController)> = Vec::new();
    // Prefab/scene files retained whole, so the Avatar-Dynamics (PhysBone) checks can read their
    // class-114 MonoBehaviour bodies + class-4 transforms (which `extract` discards).
    let mut prefab_scene_files: Vec<(String, UnityFile)> = Vec::new();
    // guid -> project-relative path of the asset the `.meta` describes.
    let mut guid_to_path: BTreeMap<String, String> = BTreeMap::new();
    // project-relative asset path -> its guid (the inverse, for our own parsed assets).
    let mut path_to_guid: BTreeMap<String, String> = BTreeMap::new();

    let assets_dir = project.assets_dir();
    if assets_dir.is_dir() {
        let files = avatar_unity_yaml::walk_assets(&assets_dir);

        // First pass: build the GUID index from `.meta` files (plus its inverse). A
        // `Foo.asset.meta` describes `Foo.asset`; references elsewhere point at it by this guid.
        for (guid, asset_path) in avatar_unity_yaml::build_guid_index(&files) {
            let rel = relative(&project.root, &asset_path);
            path_to_guid.insert(rel.clone(), guid.clone());
            guid_to_path.insert(guid, rel);
        }

        // Second pass: parse VRChat assets out of `.asset`/`.prefab`/`.unity` files.
        for path in &files {
            if !is_yaml_asset(path) {
                continue;
            }
            let rel = relative(&project.root, path);
            let Ok(text) = std::fs::read_to_string(path) else {
                continue;
            };
            let Ok(file) = UnityFile::parse(&text) else {
                continue;
            };
            for asset in extract(&file) {
                match asset {
                    VrcAsset::Parameters(p) => parameter_assets.push((rel.clone(), p)),
                    VrcAsset::Menu(m) => menu_assets.push((rel.clone(), m)),
                    VrcAsset::Descriptor(d) => descriptors.push((rel.clone(), *d)),
                }
            }
            // Prefabs and scenes can also carry Avatar-Dynamics components (PhysBones), which
            // aren't VRChat *assets* and so aren't returned by `extract`; keep the whole file.
            if matches!(
                path.extension().and_then(|e| e.to_str()),
                Some("prefab" | "unity")
            ) {
                prefab_scene_files.push((rel.clone(), file));
            }
        }

        // Third pass: animator controllers (a distinct file type, not Unity-YAML `.asset`).
        for path in &files {
            if path.extension().is_none_or(|e| e != "controller") {
                continue;
            }
            let rel = relative(&project.root, path);
            let Ok(text) = std::fs::read_to_string(path) else {
                continue;
            };
            let Ok(file) = UnityFile::parse(&text) else {
                continue;
            };
            if let Some(controller) = AnimatorController::from_file(&file) {
                controllers.push((rel, controller));
            }
        }
    }

    // --- Parameter rules ---
    let mut declared_params: BTreeSet<String> = BTreeSet::new();
    for (file, params) in &parameter_assets {
        for p in &params.parameters {
            declared_params.insert(p.name.clone());
        }
        check_parameter_budget(file, params, &mut diagnostics);
        check_duplicate_parameters(file, params, &mut diagnostics);
    }

    // --- Menu rules ---
    for (file, menu) in &menu_assets {
        check_menu_size(file, menu, &mut diagnostics);
        check_menu_param_refs(file, menu, &declared_params, &mut diagnostics);
        check_menu_empty_controls(file, menu, &mut diagnostics);
    }

    // --- Avatar Descriptor rules ---
    // The guids of the assets we recognized as Expression Parameters / Menus, so a descriptor's
    // references can be checked for both existence (resolves to a file) and the right kind.
    let param_guids = guids_of(&parameter_assets, &path_to_guid);
    let menu_guids = guids_of(&menu_assets, &path_to_guid);
    // guid -> the parsed asset, so a descriptor can be cross-checked against the *contents* of the
    // Expression Parameters and animator controllers it points at.
    let params_by_guid: BTreeMap<&str, &ExpressionParameters> = parameter_assets
        .iter()
        .filter_map(|(rel, p)| path_to_guid.get(rel).map(|g| (g.as_str(), p)))
        .collect();
    let controllers_by_guid: BTreeMap<&str, &AnimatorController> = controllers
        .iter()
        .filter_map(|(rel, c)| path_to_guid.get(rel).map(|g| (g.as_str(), c)))
        .collect();
    for (file, desc) in &descriptors {
        check_descriptor_refs(
            file,
            desc,
            &guid_to_path,
            &param_guids,
            &menu_guids,
            &mut diagnostics,
        );
        check_descriptor_visemes(file, desc, &mut diagnostics);
        check_descriptor_viseme_entries(file, desc, &mut diagnostics);
        check_descriptor_eyelook(file, desc, &mut diagnostics);
        check_descriptor_param_wiring(
            file,
            desc,
            &params_by_guid,
            &controllers_by_guid,
            &mut diagnostics,
        );
        check_descriptor_write_defaults(file, desc, &controllers_by_guid, &mut diagnostics);
    }
    if descriptors.is_empty() && project.has_avatar_sdk() {
        diagnostics.push(Diagnostic {
            severity: Severity::Info,
            code: "VRC002",
            message: "No VRC Avatar Descriptor found in any scene or prefab under Assets/".into(),
            file: None,
            hint: Some(
                "An uploadable avatar needs a GameObject with a VRC Avatar Descriptor component."
                    .into(),
            ),
        });
    }

    // --- Animator controller rules ---
    for (file, controller) in &controllers {
        check_controller(file, controller, &mut diagnostics);
    }

    // --- Project-wide expression-parameter usage (VRC012) ---
    // A superset of the per-descriptor VRC036: a declared expression parameter whose name appears
    // in no menu control, no animator condition, and no blend tree anywhere in the project.
    check_orphan_expression_params(
        &parameter_assets,
        &menu_assets,
        &controllers,
        &mut diagnostics,
    );

    // --- Avatar-Dynamics (PhysBone) rules ---
    for (file, parsed) in &prefab_scene_files {
        check_physbones(file, parsed, &mut diagnostics);
    }

    Ok(LintReport {
        project_root: project.root.display().to_string(),
        unity_version: project.unity_version.clone(),
        avatar_sdk_version: project.package_version(AVATAR_SDK).map(str::to_string),
        packages: project
            .packages
            .iter()
            .map(|p| PackageInfo {
                name: p.name.clone(),
                version: p.version.clone(),
            })
            .collect(),
        parameter_assets: parameter_assets.len(),
        menu_assets: menu_assets.len(),
        descriptors: descriptors.len(),
        controllers: controllers.len(),
        diagnostics,
    })
}

/// The set of guids belonging to a list of `(relative_path, asset)` pairs, looked up via the
/// project's path→guid index. Assets without a `.meta` are simply absent from the set.
fn guids_of<T>(
    assets: &[(String, T)],
    path_to_guid: &BTreeMap<String, String>,
) -> BTreeSet<String> {
    assets
        .iter()
        .filter_map(|(rel, _)| path_to_guid.get(rel).cloned())
        .collect()
}

fn check_parameter_budget(file: &str, params: &ExpressionParameters, out: &mut Vec<Diagnostic>) {
    let bits = params.synced_bits();
    if bits > SYNC_BUDGET_BITS {
        out.push(Diagnostic {
            severity: Severity::Error,
            code: "VRC010",
            message: format!(
                "Expression parameters use {bits} synced bits, over the {SYNC_BUDGET_BITS}-bit budget (by {})",
                bits - SYNC_BUDGET_BITS
            ),
            file: Some(file.to_string()),
            hint: Some(
                "Unsync rarely-changed parameters, or use bool/int packing to fit 256 bits.".into(),
            ),
        });
    }
}

fn check_duplicate_parameters(
    file: &str,
    params: &ExpressionParameters,
    out: &mut Vec<Diagnostic>,
) {
    let mut seen = BTreeSet::new();
    let mut reported = BTreeSet::new();
    for p in &params.parameters {
        if !seen.insert(p.name.clone()) && reported.insert(p.name.clone()) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC011",
                message: format!("Duplicate expression parameter name: '{}'", p.name),
                file: Some(file.to_string()),
                hint: Some(
                    "Remove the duplicate entry — only the first is synced and the budget counts both.".into(),
                ),
            });
        }
    }
}

fn check_menu_size(file: &str, menu: &ExpressionsMenu, out: &mut Vec<Diagnostic>) {
    if menu.controls.len() > MAX_MENU_CONTROLS {
        out.push(Diagnostic {
            severity: Severity::Error,
            code: "VRC020",
            message: format!(
                "Expression menu has {} controls, over the limit of {MAX_MENU_CONTROLS}",
                menu.controls.len()
            ),
            file: Some(file.to_string()),
            hint: Some("Move extra controls into a sub-menu.".into()),
        });
    }
}

fn check_menu_param_refs(
    file: &str,
    menu: &ExpressionsMenu,
    declared: &BTreeSet<String>,
    out: &mut Vec<Diagnostic>,
) {
    for control in &menu.controls {
        let refs = control
            .parameter
            .iter()
            .chain(control.sub_parameters.iter());
        for name in refs {
            if name.is_empty() || declared.contains(name) || is_builtin(name) {
                continue;
            }
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC021",
                message: format!(
                    "Menu control '{}' references parameter '{name}', which is not declared in any Expression Parameters asset",
                    control.name
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "Add it to the avatar's Expression Parameters, or it may be generated at build time (e.g. Modular Avatar).".into(),
                ),
            });
        }
    }
}

/// VRC022: a menu control that drives nothing — no parameter, no sub-parameters, and no sub-menu.
fn check_menu_empty_controls(file: &str, menu: &ExpressionsMenu, out: &mut Vec<Diagnostic>) {
    for control in &menu.controls {
        if control.parameter.is_none() && control.sub_parameters.is_empty() && !control.has_submenu
        {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC022",
                message: format!(
                    "Menu control '{}' drives nothing (no parameter, sub-parameters, or sub-menu)",
                    control.name
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "Assign a parameter (or point it at a sub-menu), or remove the control.".into(),
                ),
            });
        }
    }
}

fn is_builtin(name: &str) -> bool {
    BUILTIN_PARAMETERS.contains(&name)
}

/// Validate an Avatar Descriptor's cross-asset references: the Expression Parameters / Menu
/// assets it points at, and the animator controllers on its custom playable layers.
fn check_descriptor_refs(
    file: &str,
    desc: &AvatarDescriptor,
    guid_to_path: &BTreeMap<String, String>,
    param_guids: &BTreeSet<String>,
    menu_guids: &BTreeSet<String>,
    out: &mut Vec<Diagnostic>,
) {
    if desc.custom_expressions {
        check_expression_ref(
            file,
            &desc.expression_parameters,
            "Expression Parameters",
            "VRC030",
            guid_to_path,
            param_guids,
            out,
        );
        check_expression_ref(
            file,
            &desc.expressions_menu,
            "Expression Menu",
            "VRC031",
            guid_to_path,
            menu_guids,
            out,
        );
    }

    // Custom (non-default) playable layers should point at a controller that exists.
    for layer in desc.animation_layers() {
        if layer.is_default || !layer.controller.is_external() {
            continue;
        }
        let guid = layer.controller.guid.as_deref().unwrap_or_default();
        if !guid_to_path.contains_key(guid) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC032",
                message: format!(
                    "{} playable layer references an animator controller missing from the project (guid {guid})",
                    layer.type_name()
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "The .controller asset was moved or deleted; reassign it on the Avatar Descriptor.".into(),
                ),
            });
        }
    }
}

/// Check one Expression Parameters / Menu reference: that it is assigned, resolves to a file in
/// the project, and resolves to an asset of the expected kind.
fn check_expression_ref(
    file: &str,
    r: &AssetRef,
    label: &str,
    code: &'static str,
    guid_to_path: &BTreeMap<String, String>,
    expected_guids: &BTreeSet<String>,
    out: &mut Vec<Diagnostic>,
) {
    if !r.is_set() {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code,
            message: format!("Avatar uses custom expressions but no {label} asset is assigned"),
            file: Some(file.to_string()),
            hint: Some(format!(
                "Assign a {label} asset on the Avatar Descriptor, or turn off Custom Expressions."
            )),
        });
        return;
    }
    // A reference with only a local fileID (no guid) can't be resolved across files; skip it.
    let Some(guid) = r.guid.as_deref() else {
        return;
    };
    match guid_to_path.get(guid) {
        None => out.push(Diagnostic {
            severity: Severity::Warn,
            code,
            message: format!("Avatar's {label} reference points at a missing asset (guid {guid})"),
            file: Some(file.to_string()),
            hint: Some(format!(
                "The {label} asset was moved or deleted; reassign it on the Avatar Descriptor."
            )),
        }),
        Some(path) if !expected_guids.contains(guid) => out.push(Diagnostic {
            severity: Severity::Warn,
            code,
            message: format!(
                "Avatar's {label} reference resolves to '{path}', which is not a recognized {label} asset"
            ),
            file: Some(file.to_string()),
            hint: Some(format!(
                "Point the Avatar Descriptor's {label} slot at an actual {label} asset (the current target is a different asset type)."
            )),
        }),
        Some(_) => {}
    }
}

/// Viseme/lip-sync sanity checks for blend-shape lip-sync.
fn check_descriptor_visemes(file: &str, desc: &AvatarDescriptor, out: &mut Vec<Diagnostic>) {
    if !desc.uses_viseme_blendshapes() {
        return;
    }
    if !desc.viseme_mesh.is_set() {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC033",
            message: "Lip-sync is set to Viseme Blend Shape but no skinned mesh is assigned".into(),
            file: Some(file.to_string()),
            hint: Some("Assign the face mesh (VisemeSkinnedMesh) on the Avatar Descriptor.".into()),
        });
    }
    let n = desc.viseme_blendshapes.len();
    if n != VISEME_COUNT {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC033",
            message: format!(
                "Lip-sync is set to Viseme Blend Shape but {n} viseme blend shapes are configured (expected {VISEME_COUNT})"
            ),
            file: Some(file.to_string()),
            hint: Some(
                "Map all 15 visemes (sil, PP, FF, TH, DD, kk, CH, SS, nn, RR, aa, E, ih, oh, ou).".into(),
            ),
        });
    }
}

/// VRC038: when the descriptor uses viseme blend shapes and the entry count is right (so VRC033
/// won't already flag a count problem), check the 15 entries themselves — an empty/`-none-` slot
/// or a duplicate blend-shape name means a viseme isn't (uniquely) mapped.
fn check_descriptor_viseme_entries(file: &str, desc: &AvatarDescriptor, out: &mut Vec<Diagnostic>) {
    if !desc.uses_viseme_blendshapes() || desc.viseme_blendshapes.len() != VISEME_COUNT {
        return;
    }
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut dup_reported: BTreeSet<&str> = BTreeSet::new();
    for name in &desc.viseme_blendshapes {
        let trimmed = name.trim();
        if trimmed.is_empty() || trimmed == "-none-" {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC038",
                message: "A viseme blend-shape entry is empty or unmapped (-none-)".into(),
                file: Some(file.to_string()),
                hint: Some(
                    "Map every one of the 15 visemes to a blend shape on the viseme mesh.".into(),
                ),
            });
        } else if !seen.insert(trimmed) && dup_reported.insert(trimmed) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC038",
                message: format!("Duplicate viseme blend-shape entry: '{trimmed}'"),
                file: Some(file.to_string()),
                hint: Some(
                    "Each viseme should map to a distinct blend shape; a duplicate means a viseme is mis-mapped.".into(),
                ),
            });
        }
    }
}

/// Eye-look sanity checks (only when eye look is enabled).
fn check_descriptor_eyelook(file: &str, desc: &AvatarDescriptor, out: &mut Vec<Diagnostic>) {
    if !desc.enable_eye_look {
        return;
    }
    let eye = &desc.eye_look;
    if !eye.has_eye_bones() {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC034",
            message: "Eye Look is enabled but no eye bones are assigned".into(),
            file: Some(file.to_string()),
            hint: Some(
                "Assign the left/right eye bones on the Avatar Descriptor, or disable Eye Look."
                    .into(),
            ),
        });
    }
    if eye.uses_eyelid_blendshapes() && !eye.eyelids_mesh.is_set() {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC035",
            message: "Eyelids are set to Blendshapes but no eyelid skinned mesh is assigned".into(),
            file: Some(file.to_string()),
            hint: Some(
                "Assign the eyelids mesh on the Avatar Descriptor, or set Eyelid Type to None."
                    .into(),
            ),
        });
    }
}

/// Expression parameters that drive VRChat's *default* playable layers (which we skip, since they
/// resolve to no project controller), so they must not be flagged as "unused" by `VRC036`.
const DEFAULT_LAYER_EXPRESSION_PARAMS: &[&str] = &["VRCEmote", "VRCFaceBlendH", "VRCFaceBlendV"];

/// Cross-check the descriptor's Expression Parameters against the animator controllers on its
/// custom playable layers: every expression parameter should be used by some controller, and a
/// name shared with an animator parameter should have a compatible type.
fn check_descriptor_param_wiring(
    file: &str,
    desc: &AvatarDescriptor,
    params_by_guid: &BTreeMap<&str, &ExpressionParameters>,
    controllers_by_guid: &BTreeMap<&str, &AnimatorController>,
    out: &mut Vec<Diagnostic>,
) {
    if !desc.custom_expressions {
        return;
    }
    // Resolve the avatar's Expression Parameters; if it doesn't resolve, VRC030 already reported it.
    let Some(params) = desc
        .expression_parameters
        .guid
        .as_deref()
        .and_then(|g| params_by_guid.get(g))
    else {
        return;
    };

    // Collect animator parameter name -> declared raw type(s) across the *custom* playable-layer
    // controllers that resolve. (Default layers use VRChat's built-in controllers, which aren't in
    // the project, so we can't and shouldn't reason about them here.)
    let mut animator_params: BTreeMap<&str, Vec<i64>> = BTreeMap::new();
    let mut resolved_controllers = 0usize;
    for layer in desc.animation_layers() {
        if layer.is_default {
            continue;
        }
        let Some(controller) = layer
            .controller
            .guid
            .as_deref()
            .and_then(|g| controllers_by_guid.get(g))
        else {
            continue;
        };
        resolved_controllers += 1;
        for p in &controller.parameters {
            animator_params
                .entry(p.name.as_str())
                .or_default()
                .push(p.raw_type);
        }
    }
    // With no resolvable controller we can't conclude anything about wiring.
    if resolved_controllers == 0 {
        return;
    }

    for p in &params.parameters {
        match animator_params.get(p.name.as_str()) {
            None => {
                if is_builtin(&p.name) || DEFAULT_LAYER_EXPRESSION_PARAMS.contains(&p.name.as_str())
                {
                    continue;
                }
                out.push(Diagnostic {
                    severity: Severity::Warn,
                    code: "VRC036",
                    message: format!(
                        "Expression parameter '{}' is not used by any of the avatar's playable-layer animator controllers",
                        p.name
                    ),
                    file: Some(file.to_string()),
                    hint: Some(
                        "Add a matching parameter to a playable-layer controller — or ignore if it's driven by OSC, contacts, or a build-time tool (Modular Avatar / VRCFury).".into(),
                    ),
                });
            }
            Some(types) => {
                if !types
                    .iter()
                    .any(|&t| expr_matches_animator(p.value_type, t))
                {
                    out.push(Diagnostic {
                        severity: Severity::Warn,
                        code: "VRC037",
                        message: format!(
                            "Expression parameter '{}' ({}) does not match the animator parameter of the same name ({})",
                            p.name,
                            value_type_name(p.value_type),
                            types.iter().map(|&t| animator_type_name(t)).collect::<Vec<_>>().join("/")
                        ),
                        file: Some(file.to_string()),
                        hint: Some("Make the expression parameter and the animator parameter the same type.".into()),
                    });
                }
            }
        }
    }
}

/// VRC045: Write Defaults consistency *across* the avatar's playable-layer controllers. VRC044
/// flags a single controller that mixes on/off internally; this is the avatar-level view — gather
/// the write-defaults flags from every resolvable non-default playable-layer controller and flag if
/// the union mixes on and off (e.g. one layer is all-on while another is all-off). Reported per
/// descriptor, not per controller. Resolves controllers the same way as `check_descriptor_param_wiring`.
fn check_descriptor_write_defaults(
    file: &str,
    desc: &AvatarDescriptor,
    controllers_by_guid: &BTreeMap<&str, &AnimatorController>,
    out: &mut Vec<Diagnostic>,
) {
    let mut on = 0usize;
    let mut off = 0usize;
    let mut resolved_controllers = 0usize;
    for layer in desc.animation_layers() {
        if layer.is_default {
            continue;
        }
        let Some(controller) = layer
            .controller
            .guid
            .as_deref()
            .and_then(|g| controllers_by_guid.get(g))
        else {
            continue;
        };
        resolved_controllers += 1;
        for &wd in &controller.write_defaults {
            if wd {
                on += 1;
            } else {
                off += 1;
            }
        }
    }
    // Need at least two resolvable controllers to say anything *across* layers (a single one is
    // VRC044's job), and a genuine mix of on and off.
    if resolved_controllers >= 2 && on > 0 && off > 0 {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC045",
            message: format!(
                "Write Defaults is inconsistent across the avatar's playable-layer controllers ({on} states on, {off} off)"
            ),
            file: Some(file.to_string()),
            hint: Some(
                "Use one Write Defaults setting for every state on every playable layer (VRChat's templates use Off).".into(),
            ),
        });
    }
}

/// Whether a VRChat expression parameter type matches an animator parameter's raw type.
/// Animator raw types: 1 Float, 3 Int, 4 Bool, 9 Trigger.
fn expr_matches_animator(value_type: ValueType, animator_raw: i64) -> bool {
    matches!(
        (value_type, animator_raw),
        (ValueType::Int, 3) | (ValueType::Float, 1) | (ValueType::Bool, 4)
    )
}

fn value_type_name(v: ValueType) -> &'static str {
    match v {
        ValueType::Int => "Int",
        ValueType::Float => "Float",
        ValueType::Bool => "Bool",
    }
}

fn animator_type_name(raw: i64) -> &'static str {
    match raw {
        1 => "Float",
        3 => "Int",
        4 => "Bool",
        9 => "Trigger",
        _ => "Unknown",
    }
}

/// Lint an animator controller's contents: parameter references, default states, write-defaults
/// consistency, and duplicate parameters.
fn check_controller(file: &str, c: &AnimatorController, out: &mut Vec<Diagnostic>) {
    let declared: BTreeSet<&str> = c.parameter_names().collect();

    // VRC040: transition conditions must reference a declared parameter (Unity itself requires
    // this — an undeclared parameter makes the transition silently never fire). Report each name
    // once per controller.
    let mut reported_cond: BTreeSet<&str> = BTreeSet::new();
    for cond in &c.conditions {
        if !declared.contains(cond.parameter.as_str()) && reported_cond.insert(&cond.parameter) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC040",
                message: format!(
                    "Transition condition references parameter '{}', which is not declared in this controller",
                    cond.parameter
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "Add the parameter to the Animator Controller, or fix the condition's name."
                        .into(),
                ),
            });
        }
    }

    // VRC041: blend-tree parameters (respecting blend type) must also be declared.
    let mut reported_blend: BTreeSet<String> = BTreeSet::new();
    for tree in &c.blend_trees {
        for name in tree.referenced_parameters() {
            if !declared.contains(name) && reported_blend.insert(name.to_string()) {
                out.push(Diagnostic {
                    severity: Severity::Warn,
                    code: "VRC041",
                    message: format!(
                        "Blend tree uses parameter '{name}', which is not declared in this controller"
                    ),
                    file: Some(file.to_string()),
                    hint: Some("Add the parameter to the Animator Controller.".into()),
                });
            }
        }
    }

    // VRC042: a state machine with states but no default state never enters any state.
    let no_default = c
        .state_machines
        .iter()
        .filter(|sm| sm.child_state_count > 0 && !sm.has_default_state)
        .count();
    if no_default > 0 {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC042",
            message: format!("{no_default} state machine(s) have states but no default state set"),
            file: Some(file.to_string()),
            hint: Some(
                "Right-click a state in the layer and choose 'Set as Layer Default State'.".into(),
            ),
        });
    }

    // VRC043: duplicate parameter names.
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut dup_reported: BTreeSet<&str> = BTreeSet::new();
    for p in &c.parameters {
        if !seen.insert(p.name.as_str()) && dup_reported.insert(p.name.as_str()) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC043",
                message: format!("Duplicate animator parameter name: '{}'", p.name),
                file: Some(file.to_string()),
                hint: Some(
                    "Rename or delete the duplicate parameter in the Animator Controller (Unity keeps only one).".into(),
                ),
            });
        }
    }

    // VRC044: VRChat strongly recommends a single Write Defaults setting across an avatar's
    // states; mixing on and off is a common cause of broken/sticky animations.
    let on = c.write_defaults.iter().filter(|&&wd| wd).count();
    let off = c.write_defaults.len() - on;
    if on > 0 && off > 0 {
        out.push(Diagnostic {
            severity: Severity::Warn,
            code: "VRC044",
            message: format!(
                "Mixed Write Defaults across states ({on} on, {off} off); VRChat recommends a consistent setting"
            ),
            file: Some(file.to_string()),
            hint: Some(
                "Set Write Defaults the same way on every state (VRChat's templates use Off).".into(),
            ),
        });
    }
}

/// VRC012: a declared expression parameter that nothing in the *whole project* uses — no menu
/// control, no animator transition condition, no blend tree, anywhere. A superset of VRC036 (which
/// is per-descriptor and only sees the controllers a single descriptor's playable layers resolve),
/// so it's intentionally Info: it has a high false-positive rate (a name can be supplied by OSC,
/// contacts, or a build-time tool). Built-ins and the default-layer expression params are excluded.
fn check_orphan_expression_params(
    parameter_assets: &[(String, ExpressionParameters)],
    menu_assets: &[(String, ExpressionsMenu)],
    controllers: &[(String, AnimatorController)],
    out: &mut Vec<Diagnostic>,
) {
    // Every parameter name referenced anywhere in the project.
    let mut used: BTreeSet<&str> = BTreeSet::new();
    for (_, menu) in menu_assets {
        for control in &menu.controls {
            if let Some(p) = &control.parameter {
                used.insert(p.as_str());
            }
            for sp in &control.sub_parameters {
                used.insert(sp.as_str());
            }
        }
    }
    for (_, c) in controllers {
        for cond in &c.conditions {
            used.insert(cond.parameter.as_str());
        }
        for tree in &c.blend_trees {
            for name in tree.referenced_parameters() {
                used.insert(name);
            }
        }
    }

    for (file, params) in parameter_assets {
        let mut reported: BTreeSet<&str> = BTreeSet::new();
        for p in &params.parameters {
            let name = p.name.as_str();
            if name.is_empty()
                || used.contains(name)
                || is_builtin(name)
                || DEFAULT_LAYER_EXPRESSION_PARAMS.contains(&name)
            {
                continue;
            }
            if !reported.insert(name) {
                continue;
            }
            out.push(Diagnostic {
                severity: Severity::Info,
                code: "VRC012",
                message: format!(
                    "Expression parameter '{name}' is referenced by no menu control, animator condition, or blend tree anywhere in the project"
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "Wire it to a menu or animator — or ignore if it's driven by OSC, contacts, or a build-time tool (Modular Avatar / VRCFury).".into(),
                ),
            });
        }
    }
}

/// The transform hierarchy of one prefab/scene file, for resolving a PhysBone's root to the chain
/// of transforms it moves. Mirrors `avatar-stats`' `Hierarchy` (copied here to keep `avatar-lint`
/// off a dependency on `avatar-stats`).
struct PhysBoneHierarchy {
    /// Transform fileID → its child transform fileIDs (from `m_Children`).
    children: HashMap<i64, Vec<i64>>,
    /// GameObject fileID → the Transform attached to it (from `m_GameObject`).
    transform_of_gameobject: HashMap<i64, i64>,
}

impl PhysBoneHierarchy {
    fn of(file: &UnityFile) -> Self {
        let mut children = HashMap::new();
        let mut transform_of_gameobject = HashMap::new();
        for doc in &file.documents {
            // Transform (4) and RectTransform (224) both carry the hierarchy fields.
            if !matches!(doc.class_id, 4 | 224) {
                continue;
            }
            if let Some(go) = field_i64(&doc.body["m_GameObject"], "fileID") {
                transform_of_gameobject.insert(go, doc.file_id);
            }
            let kids: Vec<i64> = doc.body["m_Children"]
                .as_vec()
                .map(|list| {
                    list.iter()
                        .filter_map(|c| field_i64(c, "fileID"))
                        .filter(|&id| id != 0)
                        .collect()
                })
                .unwrap_or_default();
            children.insert(doc.file_id, kids);
        }
        PhysBoneHierarchy {
            children,
            transform_of_gameobject,
        }
    }

    /// `true` if `id` is a transform present in this file.
    fn has(&self, id: i64) -> bool {
        self.children.contains_key(&id)
    }

    /// Count the transforms in the subtree rooted at `id` (including `id`) and the chain tips
    /// (leaves) within it, skipping any transform in `ignored`. Cycle-safe via `seen`.
    fn walk(&self, id: i64, ignored: &HashSet<i64>, nodes: &mut u64, leaves: &mut u64) {
        self.walk_inner(id, ignored, &mut HashSet::new(), nodes, leaves);
    }

    fn walk_inner(
        &self,
        id: i64,
        ignored: &HashSet<i64>,
        seen: &mut HashSet<i64>,
        nodes: &mut u64,
        leaves: &mut u64,
    ) {
        if !seen.insert(id) {
            return;
        }
        *nodes += 1;
        let kids: Vec<i64> = self
            .children
            .get(&id)
            .map(|cs| {
                cs.iter()
                    .copied()
                    .filter(|c| {
                        !ignored.contains(c) && self.children.contains_key(c) && !seen.contains(c)
                    })
                    .collect()
            })
            .unwrap_or_default();
        if kids.is_empty() {
            *leaves += 1;
            return;
        }
        for child in kids {
            self.walk_inner(child, ignored, seen, nodes, leaves);
        }
    }
}

/// `true` if this `MonoBehaviour` body is a VRChat PhysBone (same structural test as `avatar-stats`).
fn is_physbone(body: &Yaml) -> bool {
    !body["endpointPosition"].is_badvalue() || !body["multiChildType"].is_badvalue()
}

/// `true` if a PhysBone's `endpointPosition` is non-zero (so VRChat appends an endpoint bone).
fn physbone_has_endpoint(body: &Yaml) -> bool {
    let ep = &body["endpointPosition"];
    ["x", "y", "z"]
        .iter()
        .any(|axis| field_f64(ep, axis).is_some_and(|v| v != 0.0))
}

/// Avatar-Dynamics (PhysBone) lint rules for one prefab/scene file: VRC050 (unresolvable root),
/// VRC051 (moves zero transforms), VRC052 (collider slots all null).
fn check_physbones(file: &str, parsed: &UnityFile, out: &mut Vec<Diagnostic>) {
    let hierarchy = PhysBoneHierarchy::of(parsed);

    for doc in &parsed.documents {
        if doc.class_id != 114 || !is_physbone(&doc.body) {
            continue;
        }
        let body = &doc.body;

        // Root: explicit `rootTransform`, else the transform on the PhysBone's own GameObject.
        let root = match field_i64(&body["rootTransform"], "fileID") {
            Some(id) if id != 0 => id,
            _ => {
                let go = field_i64(&body["m_GameObject"], "fileID").unwrap_or(0);
                hierarchy
                    .transform_of_gameobject
                    .get(&go)
                    .copied()
                    .unwrap_or(0)
            }
        };

        // VRC050: the root can't be resolved to a transform present in this file.
        if root == 0 || !hierarchy.has(root) {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC050",
                message: "A PhysBone's root transform could not be resolved in this file".into(),
                file: Some(file.to_string()),
                hint: Some(
                    "Set the PhysBone's Root Transform to a bone under it — or check the bone wasn't stripped from a nested prefab.".into(),
                ),
            });
            continue;
        }

        // VRC051: the root resolves but the PhysBone moves no transforms.
        let ignored: HashSet<i64> = body["ignoreTransforms"]
            .as_vec()
            .map(|list| {
                list.iter()
                    .filter_map(|t| field_i64(t, "fileID"))
                    .filter(|&id| id != 0)
                    .collect()
            })
            .unwrap_or_default();
        let (mut nodes, mut leaves) = (0u64, 0u64);
        hierarchy.walk(root, &ignored, &mut nodes, &mut leaves);
        let mut affected = nodes.saturating_sub(1); // the root anchor isn't simulated
        if physbone_has_endpoint(body) {
            affected += leaves;
        }
        if affected == 0 {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC051",
                message: "A PhysBone moves no transforms (its root has no child bones and no endpoint)".into(),
                file: Some(file.to_string()),
                hint: Some(
                    "Point the Root Transform at a bone with child bones, or set a non-zero Endpoint Position.".into(),
                ),
            });
        }

        // VRC052: a `colliders` list with slots but every slot a null reference. A genuinely empty
        // `colliders: []` is fine and not flagged.
        if let Some(list) = body["colliders"].as_vec()
            && !list.is_empty()
            && !list.iter().any(|c| AssetRef::parse(c).is_set())
        {
            out.push(Diagnostic {
                severity: Severity::Warn,
                code: "VRC052",
                message: format!(
                    "A PhysBone has {} collider slot(s) but none are assigned",
                    list.len()
                ),
                file: Some(file.to_string()),
                hint: Some(
                    "Assign a PhysBone Collider to each slot, or remove the empty slots.".into(),
                ),
            });
        }
    }
}

/// Files we parse as Unity YAML looking for VRChat assets.
fn is_yaml_asset(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|e| e.to_str()),
        Some("asset" | "prefab" | "unity")
    )
}

/// Discover a project (re-exported for callers that want project info without linting).
pub fn discover(path: &Path) -> Result<UnityProject> {
    UnityProject::discover(path).context("discovering Unity project")
}

#[cfg(test)]
mod tests {
    use super::*;
    use avatar_vrc_descriptor::{ExpressionParameter, ExpressionParameters, ValueType};

    /// A synced expression parameter of the given name/type, with the other fields at sensible
    /// defaults (the lint rules only read `name`, `value_type`, and `synced`).
    fn param(name: &str, value_type: ValueType) -> ExpressionParameter {
        ExpressionParameter {
            name: name.into(),
            value_type,
            default_value: 0.0,
            saved: false,
            synced: true,
        }
    }

    /// One synced `Bool` expression parameter, declared twice — the input the duplicate-parameter
    /// rule (VRC011) flags.
    fn duplicated_params() -> ExpressionParameters {
        let one = param("Toggle", ValueType::Bool);
        ExpressionParameters {
            asset_name: None,
            script_guid: None,
            parameters: vec![one.clone(), one],
        }
    }

    /// The over-budget rule (VRC010), exercised through the real `check_parameter_budget`, attaches
    /// an actionable remediation hint mentioning the 256-bit budget.
    #[test]
    fn budget_rule_populates_hint() {
        // Enough synced Float parameters (8 bits each) to blow past the 256-bit budget.
        let count = (SYNC_BUDGET_BITS / 8) + 4;
        let parameters = (0..count)
            .map(|i| param(&format!("Float{i}"), ValueType::Float))
            .collect();
        let params = ExpressionParameters {
            asset_name: None,
            script_guid: None,
            parameters,
        };

        let mut out = Vec::new();
        check_parameter_budget("Params.asset", &params, &mut out);

        let d = out
            .iter()
            .find(|d| d.code == "VRC010")
            .expect("over-budget params should produce a VRC010 diagnostic");
        let hint = d
            .hint
            .as_deref()
            .expect("VRC010 should carry a remediation hint");
        assert!(
            hint.contains("256"),
            "hint should mention the 256-bit budget: {hint}"
        );
    }

    /// The duplicate-parameter rule (VRC011) — previously hint-less — now carries a remediation
    /// hint, so it renders an indented `hint:` line in the CLI's human report.
    #[test]
    fn duplicate_param_rule_populates_hint() {
        let mut out = Vec::new();
        check_duplicate_parameters("Params.asset", &duplicated_params(), &mut out);

        let d = out
            .iter()
            .find(|d| d.code == "VRC011")
            .expect("duplicated params should produce a VRC011 diagnostic");
        assert!(
            d.hint.is_some(),
            "VRC011 should now carry a remediation hint"
        );
    }

    use avatar_vrc_descriptor::{ExpressionsMenu, MenuControl};

    fn menu_control(name: &str, parameter: Option<&str>, has_submenu: bool) -> MenuControl {
        MenuControl {
            name: name.into(),
            control_type: 102,
            parameter: parameter.map(str::to_string),
            sub_parameters: Vec::new(),
            has_submenu,
        }
    }

    /// VRC022: a control with no parameter, no sub-parameters, and no sub-menu is flagged with a
    /// hint; a control that drives a parameter is not.
    #[test]
    fn empty_menu_control_rule_populates_hint() {
        let menu = ExpressionsMenu {
            asset_name: None,
            script_guid: None,
            controls: vec![
                menu_control("Empty", None, false),
                menu_control("Toggle", Some("Foo"), false),
            ],
        };
        let mut out = Vec::new();
        check_menu_empty_controls("Menu.asset", &menu, &mut out);

        assert_eq!(out.len(), 1, "only the empty control should be flagged");
        let d = &out[0];
        assert_eq!(d.code, "VRC022");
        assert!(d.message.contains("Empty"));
        assert!(d.hint.is_some(), "VRC022 should carry a remediation hint");
    }

    fn descriptor_with_visemes(blendshapes: Vec<&str>) -> AvatarDescriptor {
        AvatarDescriptor {
            asset_name: None,
            script_guid: None,
            view_position: None,
            lip_sync_mode: 3, // VisemeBlendShape
            viseme_blendshapes: blendshapes.into_iter().map(str::to_string).collect(),
            viseme_mesh: AssetRef::default(),
            enable_eye_look: false,
            eye_look: Default::default(),
            custom_expressions: false,
            expressions_menu: AssetRef::default(),
            expression_parameters: AssetRef::default(),
            base_animation_layers: Vec::new(),
            special_animation_layers: Vec::new(),
        }
    }

    /// VRC038: with the right count of viseme entries, a duplicate and an empty/`-none-` slot are
    /// each flagged with a hint.
    #[test]
    fn viseme_entry_rule_populates_hint() {
        // 15 entries: index 0 empty, indices 1 and 2 duplicate "aa", the rest distinct.
        let mut names = vec!["", "aa", "aa"];
        for i in 0..12 {
            names.push(Box::leak(format!("v{i}").into_boxed_str()) as &str);
        }
        let desc = descriptor_with_visemes(names);
        let mut out = Vec::new();
        check_descriptor_viseme_entries("Avatar.prefab", &desc, &mut out);

        assert!(out.iter().all(|d| d.code == "VRC038"));
        assert!(
            out.iter().any(|d| d.message.contains("empty")),
            "should flag the empty entry: {out:?}"
        );
        assert!(
            out.iter().any(|d| d.message.contains("aa")),
            "should flag the duplicate entry: {out:?}"
        );
        assert!(out.iter().all(|d| d.hint.is_some()));
    }

    /// VRC050/051/052 carry hints, exercised through `check_physbones` over a synthetic file.
    #[test]
    fn physbone_rules_populate_hints() {
        // A PhysBone whose root is a transform (400) with one child bone (401) and a null
        // collider slot -> moves 1 transform (no VRC050/051), but VRC052 for the empty slot.
        const FILE: &str = "\
--- !u!1 &100
GameObject:
  m_Component: []
--- !u!4 &400
Transform:
  m_GameObject: {fileID: 100}
  m_Children:
  - {fileID: 401}
--- !u!4 &401
Transform:
  m_GameObject: {fileID: 101}
  m_Children: []
--- !u!114 &114
MonoBehaviour:
  m_GameObject: {fileID: 100}
  endpointPosition: {x: 0, y: 0, z: 0}
  rootTransform: {fileID: 400}
  ignoreTransforms: []
  colliders:
  - {fileID: 0}
";
        let file = UnityFile::parse(FILE).expect("parse");
        let mut out = Vec::new();
        check_physbones("Avatar.prefab", &file, &mut out);
        let d = out
            .iter()
            .find(|d| d.code == "VRC052")
            .expect("null collider slot should produce VRC052");
        assert!(d.hint.is_some(), "VRC052 should carry a hint");
        assert!(!out.iter().any(|d| d.code == "VRC050"));
        assert!(!out.iter().any(|d| d.code == "VRC051"));

        // A PhysBone whose root transform isn't in the file -> VRC050.
        const MISSING_ROOT: &str = "\
--- !u!114 &114
MonoBehaviour:
  m_GameObject: {fileID: 999}
  endpointPosition: {x: 0, y: 0, z: 0}
  rootTransform: {fileID: 12345}
";
        let file = UnityFile::parse(MISSING_ROOT).expect("parse");
        let mut out = Vec::new();
        check_physbones("Avatar.prefab", &file, &mut out);
        let d = out
            .iter()
            .find(|d| d.code == "VRC050")
            .expect("unresolvable root should produce VRC050");
        assert!(d.hint.is_some(), "VRC050 should carry a hint");

        // A PhysBone whose root is a leaf transform with no children and no endpoint -> VRC051.
        const NO_MOVE: &str = "\
--- !u!4 &400
Transform:
  m_GameObject: {fileID: 100}
  m_Children: []
--- !u!114 &114
MonoBehaviour:
  m_GameObject: {fileID: 100}
  endpointPosition: {x: 0, y: 0, z: 0}
  rootTransform: {fileID: 400}
";
        let file = UnityFile::parse(NO_MOVE).expect("parse");
        let mut out = Vec::new();
        check_physbones("Avatar.prefab", &file, &mut out);
        let d = out
            .iter()
            .find(|d| d.code == "VRC051")
            .expect("zero-transform PhysBone should produce VRC051");
        assert!(d.hint.is_some(), "VRC051 should carry a hint");
    }
}
